In [78]:
import pandas as pd
import numpy as np

In [79]:
students = {
    'fname': ['Alice', 'Bob', 'Charlie', 'David', 'Eve'],
    'lname': ['Smith', 'Johnson', 'Williams', 'Brown', 'Jones'],
    'age':[12,14,23,34,45],
    'average':[85, 90, 78, 92, 88]
}

In [80]:
df = pd.DataFrame(data=students)
df

     fname     lname  age  average
0    Alice     Smith   12       85
1      Bob   Johnson   14       90
2  Charlie  Williams   23       78
3    David     Brown   34       92
4      Eve     Jones   45       88

In [81]:
df.to_numpy()

array([['Alice', 'Smith', 12, 85],
       ['Bob', 'Johnson', 14, 90],
       ['Charlie', 'Williams', 23, 78],
       ['David', 'Brown', 34, 92],
       ['Eve', 'Jones', 45, 88]], dtype=object)

In [82]:
products = np.array([['sugar',450,10],
                     ['soap',800,12],
                     ['salt',300,8],
                     ['rice',500,15],
                     ['oil',600,20]])
products

array([['sugar', '450', '10'],
       ['soap', '800', '12'],
       ['salt', '300', '8'],
       ['rice', '500', '15'],
       ['oil', '600', '20']], dtype='<U21')

In [83]:
df2 = pd.DataFrame(data=products,columns=['name','price','quantity'])
df2

    name price quantity
0  sugar   450       10
1   soap   800       12
2   salt   300        8
3   rice   500       15
4    oil   600       20

In [84]:
df = pd.read_csv('Iris.csv')
df

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,5.1,3.5,1.4,0.2,Iris-setosa
1,2,4.9,3.0,1.4,0.2,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

In [85]:
pd  = pd.read_json('iris.json')
pd

    sepal_length  sepal_width  petal_length  petal_width          species
0            5.1          3.5           1.4          0.2      Iris-setosa
1            4.9          3.0           1.4          0.2      Iris-setosa
2            4.7          3.2           1.3          0.2      Iris-setosa
3            4.6          3.1           1.5          0.2      Iris-setosa
4            5.0          3.6           1.4          0.2      Iris-setosa
5            5.4          3.9           1.7          0.4      Iris-setosa
6            4.6          3.4           1.4          0.3      Iris-setosa
7            5.0          3.4           1.5          0.2      Iris-setosa
8            4.4          2.9           1.4          0.2      Iris-setosa
9            4.9          3.1           1.5          0.1      Iris-setosa
10           5.4          3.7           1.5          0.2      Iris-setosa
11           4.8          3.4           1.6          0.2      Iris-setosa
12           4.8          3.0           1.4          0.1      Iris-setosa
13           4.3          3.0           1.1          0.1      Iris-setosa
14           5.8          4.0           1.2          0.2      Iris-setosa
15           5.7          4.4           1.5          0.4      Iris-setosa
16           5.4          3.9           1.3          0.4      Iris-setosa
17           5.1          3.5           1.4          0.3      Iris-setosa
18           5.7          3.8           1.7          0.3      Iris-setosa
19           5.1          3.8           1.5          0.3      Iris-setosa
20           7.0          3.2           4.7          1.4  Iris-versicolor
21           6.4          3.2           4.5          1.5  Iris-versicolor
22           6.9          3.1           4.9          1.5  Iris-versicolor
23           5.5          2.3           4.0          1.3  Iris-versicolor
24           6.5          2.8           4.6          1.5  Iris-versicolor
25           5.7          2.8           4.5          1.3  Iris-versicolor
26           6.3          3.3           4.7          1.6  Iris-versicolor
27           4.9          2.4           3.3          1.0  Iris-versicolor
28           6.6          2.9           4.6          1.3  Iris-versicolor
29           5.2          2.7           3.9          1.4  Iris-versicolor
30           5.0          2.0           3.5          1.0  Iris-versicolor
31           5.9          3.0           4.2          1.5  Iris-versicolor
32           6.0          2.2           4.0          1.0  Iris-versicolor
33           6.1          2.9           4.7          1.4  Iris-versicolor
34           5.6          2.9           3.6          1.3  Iris-versicolor
35           6.7          3.1           4.4          1.4  Iris-versicolor

In [86]:
# TODO: reading data  from msql database

In [87]:
# Methods of exproling data
# how can u now the number of rows and columns in the data frame

# df.shape
# df.tail()
# df.head()
# df.info()

In [88]:
df.shape

(150, 6)

In [89]:
 df.tail(10)

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
140,141,6.7,3.1,5.6,2.4,Iris-virginica
141,142,6.9,3.1,5.1,2.3,Iris-virginica
142,143,5.8,2.7,5.1,1.9,Iris-virginica
143,144,6.8,3.2,5.9,2.3,Iris-virginica
144,145,6.7,3.3,5.7,2.5,Iris-virginica
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

In [90]:
 df.head(15)

    Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0    1            5.1           3.5            1.4           0.2  Iris-setosa
1    2            4.9           3.0            1.4           0.2  Iris-setosa
2    3            4.7           3.2            1.3           0.2  Iris-setosa
3    4            4.6           3.1            1.5           0.2  Iris-setosa
4    5            5.0           3.6            1.4           0.2  Iris-setosa
5    6            5.4           3.9            1.7           0.4  Iris-setosa
6    7            4.6           3.4            1.4           0.3  Iris-setosa
7    8            5.0           3.4            1.5           0.2  Iris-setosa
8    9            4.4           2.9            1.4           0.2  Iris-setosa
9   10            4.9           3.1            1.5           0.1  Iris-setosa
10  11            5.4           3.7            1.5           0.2  Iris-setosa
11  12            4.8           3.4            1.6           0.2  Iris-setosa
12  13            4.8           3.0            1.4           0.1  Iris-setosa
13  14            4.3           3.0            1.1           0.1  Iris-setosa
14  15            5.8           4.0            1.2           0.2  Iris-setosa

In [91]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             150 non-null    int64
 1   SepalLengthCm  150 non-null    float64
 2   SepalWidthCm   150 non-null    float64
 3   PetalLengthCm  150 non-null    float64
 4   PetalWidthCm   150 non-null    float64
 5   Species        150 non-null    object
dtypes: float64(4), int64(1), object(1)
memory usage: 7.2+ KB

In [92]:
df.dtypes

Id                 int64
SepalLengthCm    float64
SepalWidthCm     float64
PetalLengthCm    float64
PetalWidthCm     float64
Species           object
dtype: object

In [93]:
import pandas as pd

pd_titanic = pd.read_csv("titanic.csv")
pd_titanic

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,0,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,0,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,0,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S
5,897,0,3,"Svensson, Mr. Johan Cervin",male,14.0,0,0,7538,9.2250,NaN,S
6,898,1,3,"Connolly, Miss. Kate",female,30.0,0,0,330972,7.6292,NaN,Q
7,899,0,2,"Caldwell, Mr. Albert Francis",male,26.0,1,1,248738,29.0000,NaN,S
8,900,1,3,"Abrahim, Mrs. Joseph (Sophie Halaut Easu)",female,18.0,0,0,2657,7.2292,NaN,C
9,901,0,3,"Davies, Mr. John Samuel",male,21.0,2,0,A/4 48871,24.1500,NaN,S
10,902,0,3,"Ilieff, Mr. Ylio",male,NaN,0,0,349220,7.8958,NaN,S
11,903,0,1,"Jones, Mr. Charles Cresson",male,46.0,0,0,694,26.0000,NaN,S
12,904,1,1,"Snyder, Mrs. John Pillsbury (Nelle Stevenson)",female,23.0,1,0,21228,82.2667,B45,S
13,905,0,2,"Howard, Mr. Benjamin",male,63.0,1,0,24065,26.0000,NaN,S
14,906,1,1,"Chaffee, Mrs. Herbert Fuller (Carrie Constance...",female,47.0,1,0,W.E.P. 5734,61.1750,E31,S
15,907,1,2,"del Carlo, Mrs. Sebastiano (Argenia Genovesi)",female,24.0,1,0,SC/PARIS 2167,27.7208,NaN,C
16,908,0,2,"Keane, Mr. Daniel",male,35.0,0,0,233734,12.3500,NaN,Q
17,909,0,3,"Assaf, Mr. Gerios",male,21.0,0,0,2692,7.2250,NaN,C
18,910,1,3,"Ilmakangas, Miss. Ida Livija",female,27.0,1,0,STON/O2. 3101270,7.9250,NaN,S
19,911,1,3,"Assaf Khalil, Mrs. Mariana (Miriam)",female,45.0,0,0,2696,7.2250,NaN,C
20,912,0,1,"Rothschild, Mr. Martin",male,55.0,1,0,PC 17603,59.4000,NaN,C
21,913,0,3,"Olsen, Master. Artur Karl",male,9.0,0,1,C 17368,3.1708,NaN,S
22,914,1,1,"Flegenheim, Mrs. Alfred (Antoinette)",female,NaN,0,0,PC 17598,31.6833,NaN,S
23,915,0,1,"Williams, Mr. Richard Norris II",male,21.0,0,1,PC 17597,61.3792,NaN,C
24,916,1,1,"Ryerson, Mrs. Arthur Larned (Emily Maria Borie)",female,48.0,1,3,PC 17608,262.3750,B57 B59 B63 B66,C
25,917,0,3,"Robins, Mr. Alexander A",male,50.0,1,0,A/5. 3337,14.5000,NaN,S
26,918,1,1,"Ostby, Miss. Helene Ragnhild",female,22.0,0,1,113509,61.9792,B36,C
27,919,0,3,"Daher, Mr. Shedid",male,22.5,0,0,2698,7.2250,NaN,C
28,920,0,1,"Brady, Mr. John Bertram",male,41.0,0,0,113054,30.5000,A21,S
29,921,0,3,"Samaan, Mr. Elias",male,NaN,2,0,2662,21.6792,NaN,C
30,922,0,2,"Louch, Mr. Charles Alexander",male,50.0,1,0,SC/AH 3085,26.0000,NaN,S
31,923,0,2,"Jefferys, Mr. Clifford Thomas",male,24.0,2,0,C.A. 31029,31.5000,NaN,S
32,924,1,3,"Dean, Mrs. Bertram (Eva Georgetta Light)",female,33.0,1,2,C.A. 2315,20.5750,NaN,S
33,925,1,3,"Johnston, Mrs. Andrew G (Elizabeth Lily Watson)",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
34,926,0,1,"Mock, Mr. Philipp Edmund",male,30.0,1,0,13236,57.7500,C78,C
35,927,0,3,"Katavelas, Mr. Vassilios",male,18.5,0,0,2682,7.2292,NaN,C
36,928,1,3,"Roth, Miss. Sarah A",female,NaN,0,0,342712,8.0500,NaN,S
37,929,1,3,"Cacic, Miss. Manda",female,21.0,0,0,315087,8.6625,NaN,S
38,930,0,3,"Sap, Mr. Julius",male,25.0,0,0,345768,9.5000,NaN,S
39,931,0,3,"Hee, Mr. Ling",male,NaN,0,0,1601,56.4958,NaN,S
40,932,0,3,"Karun, Mr. Franz",male,39.0,0,1,349256,13.4167,NaN,C
41,933,0,1,"Franklin, Mr. Thomas Parham",male,NaN,0,0,113778,26.5500,D34,S
42,934,0,3,"Goldsmith, Mr. Nathan",male,41.0,0,0,SOTON/O.Q. 3101263,7.8500,NaN,S
43,935,1,2,"Corbett, Mrs. Walter H (Irene Colvin)",female,30.0,0,0,237249,13.0000,NaN,S
44,936,1,1,"Kimball, Mrs. Edwin Nelson Jr (Gertrude Parsons)",female,45.0,1,0,11753,52.5542,D19,S

In [96]:
# reading column data
pd_titanic['Age']

0     34.5
1     47.0
2     62.0
3     27.0
4     22.0
5     14.0
6     30.0
7     26.0
8     18.0
9     21.0
10     NaN
11    46.0
12    23.0
13    63.0
14    47.0
15    24.0
16    35.0
17    21.0
18    27.0
19    45.0
20    55.0
21     9.0
22     NaN
23    21.0
24    48.0
25    50.0
26    22.0
27    22.5
28    41.0
29     NaN
30    50.0
31    24.0
32    33.0
33     NaN
34    30.0
35    18.5
36     NaN
37    21.0
38    25.0
39     NaN
40    39.0
41     NaN
42    41.0
43    30.0
44    45.0
Name: Age, dtype: float64

In [97]:
# get unique values in a column
pd_titanic['Age'].unique()

array([34.5, 47. , 62. , 27. , 22. , 14. , 30. , 26. , 18. , 21. ,  nan,
       46. , 23. , 63. , 24. , 35. , 45. , 55. ,  9. , 48. , 50. , 22.5,
       41. , 33. , 18.5, 25. , 39. ])

In [98]:
# TODO: loc and iloc

pd_titanic.iloc[:3, :3]

   PassengerId  Survived  Pclass
0          892         0       3
1          893         1       3
2          894         0       2

In [102]:
# get the name and gender
pd_titanic.loc[:,'Name':'Sex']

                                                 Name     Sex
0                                    Kelly, Mr. James    male
1                    Wilkes, Mrs. James (Ellen Needs)  female
2                           Myles, Mr. Thomas Francis    male
3                                    Wirz, Mr. Albert    male
4        Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female
5                          Svensson, Mr. Johan Cervin    male
6                                Connolly, Miss. Kate  female
7                        Caldwell, Mr. Albert Francis    male
8           Abrahim, Mrs. Joseph (Sophie Halaut Easu)  female
9                             Davies, Mr. John Samuel    male
10                                   Ilieff, Mr. Ylio    male
11                         Jones, Mr. Charles Cresson    male
12      Snyder, Mrs. John Pillsbury (Nelle Stevenson)  female
13                               Howard, Mr. Benjamin    male
14  Chaffee, Mrs. Herbert Fuller (Carrie Constance...  female
15      del Carlo, Mrs. Sebastiano (Argenia Genovesi)  female
16                                  Keane, Mr. Daniel    male
17                                  Assaf, Mr. Gerios    male
18                       Ilmakangas, Miss. Ida Livija  female
19                Assaf Khalil, Mrs. Mariana (Miriam)  female
20                             Rothschild, Mr. Martin    male
21                          Olsen, Master. Artur Karl    male
22               Flegenheim, Mrs. Alfred (Antoinette)  female
23                    Williams, Mr. Richard Norris II    male
24    Ryerson, Mrs. Arthur Larned (Emily Maria Borie)  female
25                            Robins, Mr. Alexander A    male
26                       Ostby, Miss. Helene Ragnhild  female
27                                  Daher, Mr. Shedid    male
28                            Brady, Mr. John Bertram    male
29                                  Samaan, Mr. Elias    male
30                       Louch, Mr. Charles Alexander    male
31                      Jefferys, Mr. Clifford Thomas    male
32           Dean, Mrs. Bertram (Eva Georgetta Light)  female
33    Johnston, Mrs. Andrew G (Elizabeth Lily Watson)  female
34                           Mock, Mr. Philipp Edmund    male
35                           Katavelas, Mr. Vassilios    male
36                                Roth, Miss. Sarah A  female
37                                 Cacic, Miss. Manda  female
38                                    Sap, Mr. Julius    male
39                                      Hee, Mr. Ling    male
40                                   Karun, Mr. Franz    male
41                        Franklin, Mr. Thomas Parham    male
42                              Goldsmith, Mr. Nathan    male
43              Corbett, Mrs. Walter H (Irene Colvin)  female
44   Kimball, Mrs. Edwin Nelson Jr (Gertrude Parsons)  female

In [103]:
# mean max median min :TODO

# DATA CLEANING(dropna)
# dropna - drop the rows with missing values
# fillna - fill the missing values with a specific value
# duplicates - drop duplicates
# notnull - check for non null values
# isnull - check for null values
# drop_duplicates - drop duplicates ,drops but does not return a new data frame. maintains the original data frame
# duplicated - returns a boolean series indicating whether each row is a duplicate or not

In [ ]:
# TODO: data transformation